### ISSUE TITLE
Code reproduction

### ISSUE THREAD

**Issue by yusun-nlp** [LindgeW/MetaAug4NER#1]
Hi, I'm trying to reproduce your results. Could you please provide me more specific instructions for running the program in different situations? Such as baseline, mixup and meta-reweighting. 
Thanks!

**Comment by LindgeW** [comment]
Hi. Please firstly prepare the pseudo-labled training data according to the README, and run the instructions from `run.sh`, remember to adjust the hyperparameters. Thank you.
