### ISSUE TITLE
Chinese datasets

### ISSUE THREAD

**Issue by Victor-xx** [LindgeW/MetaAug4NER#2]
Dear author, can you share the Chinese datasets involved in the paper with me? I can't find the datasets with CWS and NER. My email: zunjiezhu@126.com 。 Thank you very much!

**Comment by LindgeW** [comment]
> Dear author, can you share the Chinese datasets involved in the paper with me? I can't find the datasets with CWS and NER. My email: [zunjiezhu@126.com](mailto:zunjiezhu@126.com) 。 Thank you very much!

Ok!

**Comment by Victor-xx** [comment]
Thank you very much!

**Comment by bbhh123** [comment]
Dear author, can you share the Chinese datasets involved in the paper with me? I can't find the datasets with CWS and NER. My email: b17860701816@163.com 。 Thank you very much!

**Comment by LindgeW** [comment]
> Dear author, can you share the Chinese datasets involved in the paper with me? I can't find the datasets with CWS and NER. My email: [b17860701816@163.com](mailto:b17860701816@163.com) 。 Thank you very much!

Done！

**Comment by bbhh123** [comment]
> > 亲爱的作者，能把论文中涉及的中文数据集分享给我吗？我找不到带有 CWS 和 NER 的数据集。我的邮箱：[b17860701816@163.com](mailto:b17860701816@163.com)。非常感谢！
> 
> 完毕！

**Comment by bbhh123** [comment]
Thank you very much！
